name:                fpTask2
version:             0.1.0.0
github:              "gavaharlal/fpTask2"
license:             BSD3
author:              "Alexander"
maintainer:          "gavaharlal@yandex.ru"
copyright:           "2020 Alexander"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gavaharlal/fpTask2#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp

library:
  source-dirs: src
  dependencies:
    - matrix
    - mtl
    - monad-par
    - parallel
    - memoize
    - containers
    - random
    - text
    - req
    - unordered-containers
    - vector

  default-extensions:
    - LambdaCase
    - TemplateHaskell
    - DataKinds
    - TypeOperators
    - NamedFieldPuns
    - DuplicateRecordFields
    - OverloadedStrings

executables:
  fpTask2-exe:
    main:                Main
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpTask2
    - matrix

  fpTask2-front:
    main:                Main
    source-dirs:         front
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fpTask2
      - brick
      - vty

    default-extensions:
      - OverloadedStrings
      - NamedFieldPuns
      - DataKinds
      - TemplateHaskell
      - LambdaCase

tests:
  fpTask2-test:
    main:                Spec
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpTask2
    - matrix
    - HUnit
    - unordered-containers
    - parallel
    - random